### ISSUE TITLE
openjdk@8 is not compatible with m1 mac

### ISSUE THREAD

**Issue by sxzz** [junbaor/homebrew-brew#1]
```
Error: openjdk@8: no bottle available!
You can try to install from source with:
  brew install --build-from-source openjdk@8
```

Maybe we can upgrade it to openjdk 11 or 17?

**Comment by junbaor** [comment]
@sxzz 对 m1 版本的 homebrew 不太了解，程序对 jdk 的要求是 >= 8
你可以运行 `brew edit junbaor/brew/jike-cli` 在本地修改依赖版本试试。
把 `depends_on 'openjdk@8'` 修改为 `depends_on 'openjdk@11'`，然后 `brew install junbaor/brew/jike-cli`

**Comment by sxzz** [comment]
我测试了可以，我提个PR改改？

**Comment by junbaor** [comment]
可以的, 欢迎。
